### ISSUE TITLE
Run mpd programmatically

### ISSUE THREAD

**Issue by ewnd9** [mink0/mu-player#1]
"Start MPD daemon. Test if it is running by typing telnet localhost 6600. You should see OK MPD response." 
You could run `mpd` via [child_process api](https://nodejs.org/api/child_process.html) and check if it is already running via [telnet](https://github.com/mkozjak/node-telnet-client) or [ps](https://www.npmjs.com/package/ps-node) command.
Also, you could show instruction how to install `mpd` if `mpd` executable is not found :)

**Comment by mink0** [comment]
Thanks for the insight, @ewnd9! Actually MPD is installed as autostarting service in Linux. So no need to start it manually from the application. As for the OS X: yes, no autostart by default after installing it via homebrew and yes, mpd is halting sometimes on  OS X.

First, I will check if MPD is running on app start and add more descriptive error message. Second, I need to reconnect my client if connection is lost. I will do it later if somebody will ask me about it.

**Comment by mink0** [comment]
Added error message in d0e699c2d08a83c12800e266f027241b6c934129
